const sb=supabase.createClient('https://zwvqzywizqnohvedsbni.supabase.co','sb_publishable_Ex4VK3dEdR0t_5hlBJB9FQ_nPmIDTCO');
let profile=null,quiz=null,qi=0,ans=[],tid=null,left=0;
const TESTS=[{id:'ap',title:'Math AP',mins:5,qs:[{q:'d = ?',o:['a2-a1','a1-a2','a1+a2'],a:0},{q:'nth term?',o:['a+(n-1)d','a+nd','nd'],a:0},{q:'1,3,5,7 d?',o:['1','2','3'],a:1},{q:'Sn starts?',o:['n/2[2a+(n-1)d]','n(a+d)','na'],a:0},{q:'a=2,d=3,5th?',o:['14','11','17'],a:0}]},{id:'lt',title:'Light',mins:4,qs:[{q:'Speed of light?',o:['3e8 m/s','3e6','300'],a:0},{q:'i equals?',o:['r','2r','0'],a:0},{q:'Concave use?',o:['Headlight','Never','Plane'],a:0},{q:'Refraction when?',o:['Medium changes','Same','Vacuum'],a:0}]}];
const map={h:'ph',live:'plive',courses:'pcourses',tests:'ptests',study:'pstudy',ai:'pai',results:'presults',fees:'pfees',certificates:'pcert',rewards:'prewards',doubt:'pdoubt',notices:'pnotices',admission:'padm',faculty:'pfaculty',gallery:'pgallery',attendance:'patt',community:'pcommunity',contact:'pcontact',about:'pabout',p:'pprof',admin:'padmin',teach:'pteach',quiz:'pquiz',res:'pres'};
function gp(){try{return JSON.parse(localStorage.getItem('rbs_prog')||'{"pts":0,"streak":0,"tests":0,"last":"","best":0}')}catch(e){return{pts:0,streak:0,tests:0,last:'',best:0}}}
function sp(p){localStorage.setItem('rbs_prog',JSON.stringify(p));updStats()}
function touchStreak(){const p=gp();const d=new Date().toISOString().slice(0,10);if(p.last===d)return;const y=new Date(Date.now()-864e5).toISOString().slice(0,10);p.streak=(p.last===y)?(p.streak||0)+1:1;p.last=d;sp(p)}
function updStats(){const p=gp();const el=id=>document.getElementById(id);if(el('stPts'))stPts.textContent=p.pts||0;if(el('stStreak'))stStreak.textContent=p.streak||0;if(el('stTests'))stTests.textContent=p.tests||0;if(el('rwPts'))rwPts.textContent=p.pts||0;if(el('rwStreak'))rwStreak.textContent=(p.streak||0)+' days';if(el('rwTests'))rwTests.textContent=p.tests||0;if(el('bd1'))bd1.textContent=(p.tests>=1)?'✓':'—';if(el('bd2'))bd2.textContent=(p.best>=80)?'✓':'—';if(el('bd3'))bd3.textContent=(p.streak>=3)?'✓':'—'}
function show(id){document.querySelectorAll('.sc').forEach(x=>x.classList.remove('on'));document.getElementById(id).classList.add('on')}
function go(p){document.querySelectorAll('.pg').forEach(x=>x.classList.remove('on'));document.getElementById(map[p]||'ph').classList.add('on');document.querySelectorAll('.bn button').forEach(b=>b.classList.toggle('on',b.dataset.p===p||(p==='h'&&b.dataset.p==='h')));if(p==='tests')renderT();if(p==='study')loadS();if(p==='results')loadR();if(p==='notices')loadN();if(p==='p')fillP();if(p==='admin')loadA();if(p==='live')loadLive();if(p==='h'){loadHN();showTT();updStats();recoHome()}if(p==='rewards')updStats();if(p==='certificates')genCert()}
function tab(t){tl.classList.toggle('on',t==='l');ts.classList.toggle('on',t==='s');bl.style.display=t==='l'?'block':'none';bs.style.display=t==='s'?'block':'none'}
async function signup(){const email=se.value.trim(),pass=sw.value,name=sn.value.trim(),phone=sp.value.trim(),role=(document.querySelector('input[name=role]:checked')||{}).value||'student';if(!email||pass.length<6){am.innerHTML='<div class="msg err">Email+pass min6</div>';return}const{data,error}=await sb.auth.signUp({email,password:pass,options:{data:{full_name:name,phone,role,class_level:sclass.value}}});if(error){am.innerHTML='<div class="msg err">'+error.message+'</div>';return}if(data.user)await sb.from('profiles').upsert({id:data.user.id,full_name:name,phone,role,class_level:sclass.value||null});am.innerHTML='<div class="msg ok">OK — Login</div>';tab('l')}
async function login(){const{error}=await sb.auth.signInWithPassword({email:le.value.trim(),password:lp.value});if(error){am.innerHTML='<div class="msg err">'+error.message+'</div>';return}await loadP();enter()}
async function logout(){await sb.auth.signOut();profile=null;show('au')}
async function loadP(){const{data:{user}}=await sb.auth.getUser();if(!user)return;let{data}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(!data){const m=user.user_metadata||{};data={id:user.id,full_name:m.full_name||user.email,role:m.role||'student',phone:m.phone||''};await sb.from('profiles').upsert(data)}profile=data}
function enter(){show('ap');gr.textContent='Hi, '+((profile&&profile.full_name)||'Student').split(' ')[0];touchStreak();go('h')}
function fillP(){pn.textContent=(profile&&profile.full_name)||'—';pro.textContent=((profile&&profile.role)||'student').toUpperCase()}
function showTT(){tt.style.display=(profile&&(profile.role==='teacher'||profile.role==='admin'))?'block':'none'}
function recoHome(){const cl=(profile&&profile.class_level)||'';const items=cl.includes('9')||cl==='10'?['Class 10 Math AP test','Science Light chapter','Board prep notes']:['Foundation all subjects','Weekly practice test','AI Tutor doubt help'];reco.innerHTML=items.map(t=>'<div class=lc><div class=f><b>'+t+'</b></div><button class=chip chip-o onclick="go(\'tests\')">Go</button></div>').join('')}
async function loadHN(){const{data}=await sb.from('notices').select('title,body').eq('is_published',true).order('created_at',{ascending:false}).limit(1);hn.innerHTML=data&&data[0]?'<div class=lc><div class=f><b>'+data[0].title+'</b><span class=s>'+(data[0].body||'')+'</span></div></div>':''}
function renderT(){tlst.innerHTML=TESTS.map(t=>'<div class=lc><div class=f><b>'+t.title+'</b><span class=s>'+t.qs.length+'Q · '+t.mins+'m</span></div><button class=chip onclick="start(\''+t.id+'\')">Start</button></div>').join('')}
function start(id){quiz=TESTS.find(t=>t.id===id);qi=0;ans=Array(quiz.qs.length).fill(null);left=quiz.mins*60;go('quiz');drawQ();timer()}
function timer(){clearInterval(tid);const tick=()=>{tm.textContent=String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0');if(left<=0){clearInterval(tid);finish();return}left--};tick();tid=setInterval(tick,1000)}
function drawQ(){const x=quiz.qs[qi];qn.textContent='Q'+(qi+1)+'/'+quiz.qs.length;qt.textContent=x.q;qo.innerHTML=x.o.map((o,i)=>'<button class="opt'+(ans[qi]===i?' sel':'')+'" onclick="pick('+i+')">'+(i+1)+'. '+o+'</button>').join('');qnxt.textContent=qi===quiz.qs.length-1?'Submit':'Next'}
function pick(i){ans[qi]=i;drawQ()}
function nxt(){if(ans[qi]==null){alert('Choose');return}if(qi<quiz.qs.length-1){qi++;drawQ()}else finish()}
function finish(){clearInterval(tid);let c=0;quiz.qs.forEach((q,i)=>{if(ans[i]===q.a)c++});const pct=Math.round(c/quiz.qs.length*100);rs.textContent=pct+'%';rd.textContent=c+'/'+quiz.qs.length;const pts=c*10;const p=gp();p.pts=(p.pts||0)+pts;p.tests=(p.tests||0)+1;p.best=Math.max(p.best||0,pct);sp(p);rp.textContent='+'+pts+' points earned';go('res');try{const L=JSON.parse(localStorage.getItem('rbs_r')||'[]');L.unshift({t:quiz.title,c,n:quiz.qs.length,pct});localStorage.setItem('rbs_r',JSON.stringify(L.slice(0,20)))}catch(e){}}
function loadR(){try{const L=JSON.parse(localStorage.getItem('rbs_r')||'[]');rl.innerHTML=L.length?L.map(x=>'<div class=lc><div class=f><b>'+x.t+'</b><span class=s>'+x.c+'/'+x.n+'</span></div><b style=color:var(--g)>'+x.pct+'%</b></div>').join(''):'<p style=color:var(--m)>None</p>'}catch(e){rl.innerHTML='—'}}
async function loadS(){const{data,error}=await sb.from('materials').select('*').order('created_at',{ascending:false});if(error||!data||!data.length){sl.innerHTML='<div class=lc><div class=f><b>Math Notes</b><span class=s>Teacher upload</span></div></div>';return}sl.innerHTML=data.map(m=>'<div class=lc><div class=f><b>'+m.title+'</b></div>'+(m.file_url?'<a class=chip href="'+m.file_url+'" target=_blank>Open</a>':'')+'</div>').join('')}
async function saveMat(){const title=mt.value.trim();if(!title){mm.innerHTML='<div class="msg err">Title</div>';return}const{error}=await sb.from('materials').insert({title,file_url:mu.value.trim()||null});mm.innerHTML=error?'<div class="msg err">'+error.message+'</div>':'<div class="msg ok">Saved</div>'}
function saveLive(){const title=ltitle.value.trim(),url=lurl.value.trim();if(!title||!url){lm.innerHTML='<div class="msg err">Title+URL</div>';return}try{const L=JSON.parse(localStorage.getItem('rbs_live')||'[]');L.unshift({title,url,by:(profile&&profile.full_name)||'T'});localStorage.setItem('rbs_live',JSON.stringify(L.slice(0,15)));lm.innerHTML='<div class="msg ok">Posted</div>'}catch(e){lm.innerHTML='<div class="msg err">Err</div>'}}
function loadLive(){let L=[];try{L=JSON.parse(localStorage.getItem('rbs_live')||'[]')}catch(e){}if(!L.length){liveList.innerHTML='<div class=lc><div class=f><b>Sample class</b><span class=s>Teacher posts link</span></div><span class=chip chip-o>Soon</span></div>';return}liveList.innerHTML=L.map(x=>'<div class=lc><div class=f><b>'+x.title+'</b></div><a class=chip href="'+x.url+'" target=_blank>Join</a></div>').join('')}
async function sendEnq(){const name=en.value.trim(),phone=ep.value.trim();if(!name||!phone){er.innerHTML='<div class="msg err">Name+phone</div>';return}const{error}=await sb.from('enquiries').insert({student_name:name,phone,class_interested:ec.value,message:em.value.trim(),status:'new'});er.innerHTML=error?'<div class="msg err">'+error.message+'</div>':'<div class="msg ok">Saved</div>'}
function sendDoubt(){const q=dq.value.trim();if(!q){dm.innerHTML='<div class="msg err">Likho</div>';return}try{const D=JSON.parse(localStorage.getItem('rbs_doubts')||'[]');D.unshift({q,at:Date.now()});localStorage.setItem('rbs_doubts',JSON.stringify(D.slice(0,30)));dm.innerHTML='<div class="msg ok">Saved</div>';dq.value=''}catch(e){}}
async function loadN(){const{data}=await sb.from('notices').select('*').eq('is_published',true).order('created_at',{ascending:false});nl.innerHTML=(data&&data.length)?data.map(n=>'<div class=lc><div class=f><b>'+n.title+'</b><span class=s>'+(n.body||'')+'</span></div></div>').join(''):'<p style=color:var(--m)>None</p>'}
async function loadA(){const{data,error}=await sb.from('enquiries').select('*').order('created_at',{ascending:false}).limit(30);if(error){ab.innerHTML='<div class="msg err">'+error.message+'</div>';return}ab.innerHTML=(data&&data.length)?data.map(e=>'<div class=lc><div class=f><b>'+e.student_name+'</b><span class=s>'+e.phone+'</span></div></div>').join(''):'<p style=color:var(--m)>None</p>'}
function aiReply(q){q=(q||'').toLowerCase();
if(/ap|arithmetic|progression|nth|common difference/.test(q))return 'Arithmetic Progression (AP):\n• Common difference d = a₂ − a₁\n• nth term: aₙ = a + (n−1)d\n• Sum: Sₙ = n/2 [2a + (n−1)d]\nExample: 2,5,8,11… d=3';
if(/light|reflect|mirror|refraction|concave|convex/.test(q))return 'Light:\n• Reflection: ∠i = ∠r\n• Concave mirror: headlights, shaving\n• Refraction: light changes medium (air→water)\n• Speed of light ≈ 3×10⁸ m/s';
if(/photo|plant|chlorophyll|oxygen/.test(q))return 'Photosynthesis:\n6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂ (sunlight, chlorophyll)\nPlants make food and release oxygen.';
if(/gravity|newton|force|mass/.test(q))return 'Newton: F = ma. Gravity pulls objects toward Earth. Weight = mass × g (g≈9.8 m/s²).';
if(/fraction|percent|ratio|algebra|equation/.test(q))return 'Tip: fractions — same denominator add numerators. Percent: x% of N = (x/100)×N. Linear equation: isolate variable on one side.';
return 'Achha sawal! Main Class 1–10 Math/Science/SST help karta hoon.\nTry: "AP formula", "reflection rule", "photosynthesis".\nDetailed doubt ke liye Teacher panel ya WhatsApp 8873880542 use karo.';
}
function askAI(){const q=aiQ.value.trim();if(!q)return;const box=chatBox;box.innerHTML+='<div class="bubble me">'+q.replace(/</g,'<')+'</div>';const a=aiReply(q);box.innerHTML+='<div class="bubble ai">'+a.replace(/\\n/g,'<br>')+'</div>';aiQ.value='';box.scrollTop=box.scrollHeight;const p=gp();p.pts=(p.pts||0)+2;sp(p)}
function quickAI(t){aiQ.value=t;askAI()}
function genCert(){const p=gp();certName.textContent=(profile&&profile.full_name)||'RBS Student';certMeta.textContent='Points: '+(p.pts||0)+' · Tests: '+(p.tests||0)+' · Best: '+(p.best||0)+'%'}
function recordPay(){payMsg.innerHTML='<div class="msg ok">Note saved — UPI/WhatsApp se pay karke director ko message bhejo</div>';try{const L=JSON.parse(localStorage.getItem('rbs_pay')||'[]');L.unshift({amt:payAmt.value,at:Date.now()});localStorage.setItem('rbs_pay',JSON.stringify(L.slice(0,20)))}catch(e){}}
if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
setTimeout(async()=>{const{data:{session}}=await sb.auth.getSession();if(session){await loadP();enter()}else show('au')},700);
